/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2023-05-26 01:16:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Board Register Page</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h1>Board Register Page</h1>\n");
      out.write("\n");
      out.write("<form action=\"/brd/insert\" method=\"post\" enctype=\"multipart/form-data\">>\n");
      out.write("제목 : <input type=\"text\" id = \"title\" name=\"title\"/><p id=\"title_text\"></p>\n");
      out.write("작성자 : <input type=\"text\" name=\"writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly/><br><p></p>\n");
      out.write("내용 : <textarea rows=\"3\" cols=\"30\" name=\"post\"></textarea><br>\n");
      out.write("이미지업로드 : <input type=\"file\" id=\"file\" name=\"imgfile\" accept=\"image/png, image/jpeg, image/jpg, image/bmp, image/gif\" onchange=\"setThumbnail(event)\">\n");
      out.write("<div id=\"image_container\"></div><br>\n");
      out.write("<button type=\"submit\" id=\"smt\" disabled=\"disabled\">완료</button>\n");
      out.write("</form>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("	var regExp = /^[a-zA-Z0-9ㄱ-ㅎ가-힣\\s]{2,50}$/;\n");
      out.write("	var title = document.getElementById('title');\n");
      out.write("	var smt = document.getElementById('smt'); \n");
      out.write("	title.addEventListener('input', () => {\n");
      out.write("			\n");
      out.write("		if(regExp.test(title.value)){\n");
      out.write("			title.style.borderColor = 'green';\n");
      out.write("			document.getElementById('title_text').innerHTML = '';\n");
      out.write("			smt.disabled = false;\n");
      out.write("		}else{\n");
      out.write("			title.style.borderColor = 'red';\n");
      out.write("			document.getElementById('title_text').innerHTML = '최소 2글자는 입력해야합니다';\n");
      out.write("			smt.disabled = true;\n");
      out.write("		}\n");
      out.write("	 });\n");
      out.write("	\n");
      out.write("    function setThumbnail(event) {\n");
      out.write("       	document.getElementById(\"image_container\").innerHTML = \"\";\n");
      out.write("        var reader = new FileReader();\n");
      out.write("\n");
      out.write("        reader.onload = function(event) {\n");
      out.write("          var img = document.createElement(\"img\");\n");
      out.write("          img.setAttribute(\"src\", event.target.result);\n");
      out.write("          img.style.width = \"75px\";\n");
      out.write("          img.style.height = \"75px\";\n");
      out.write("          document.querySelector(\"div#image_container\").appendChild(img);\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        reader.readAsDataURL(event.target.files[0]);\n");
      out.write("      }\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
